---
- name: Add Bitnami Helm repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Deploy PostgreSQL
  kubernetes.core.helm:
    name: my-postgres
    chart_ref: bitnami/postgresql
    release_namespace: "{{ postgres_namespace }}"
    create_namespace: true
    values: "{{ lookup('template', 'postgres-values.yaml.j2') | from_yaml }}"

- name: Wait for PostgreSQL to be ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ postgres_namespace }}"
    label_selectors:
      - app.kubernetes.io/name=postgresql
  register: postgres_pods
  until: postgres_pods.resources[0].status.phase == "Running"
  retries: 10
  delay: 30

